Append the array contents, not the array itself
Without this, lines becomes:

```
[
  ...,
  "<!-- SCHEMA_DEV: TEMPLATE #{key} - begin -->\n",
  "<!-- These lines are auto-inserted from a schema_dev template -->\n",
  [
    "template line 1\n",
    "template line 2\n",
    ...
  ],
  "\n",
  "<!-- SCHEMA_DEV: TEMPLATE #{key} - end -->\n",
  ...
]
```

Then subsequent replacements fail because they choke on the array in the
middle. Like:

```
.../schema_dev-4.2.0/lib/schema_dev/readme.rb:68:in `!~': undefined method `=~' for ["As usual:\n", "\n", "```ruby\n", "gem \"<%= gem_name %>\"                # in a Gemfile\n", "gem.add_dependency \"<%= gem_name %>\" # in a .gemspec\n", "```\n"]:Array (NoMethodError)

  before = lines.take_while { |line| line !~ pattern }
                                          ^^
  from .../schema_dev-4.2.0/lib/schema_dev/readme.rb:68:in `block in replace_block'
```

After this change:

```
[
  ...,
  "<!-- SCHEMA_DEV: TEMPLATE #{key} - begin -->\n",
  "<!-- These lines are auto-inserted from a schema_dev template -->\n",
  "template line 1\n",
  "template line 2\n",
  ...,
  "\n",
  "<!-- SCHEMA_DEV: TEMPLATE #{key} - end -->\n",
  ...
]
```